name: Unit Tests

on:
  workflow_call:  # Allow this workflow to be called by others
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.os }}, Node ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['18.x', '20.x', '22.x']
    
    env:
      # Disable font scanning on Linux for speed
      APPSHOT_DISABLE_FONT_SCAN: ${{ startsWith(matrix.os, 'ubuntu') && '1' || '' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Run unit tests
        run: npm run test:unit
        env:
          CI: true
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-unit-${{ matrix.os }}-node${{ matrix.node }}
          path: |
            test-results/
            coverage/
          retention-days: 7