name: CLI Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose output'
        required: false
        default: 'false'

jobs:
  cli-integration:
    name: CLI Integration Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Link CLI globally
        run: npm link
      
      - name: Verify appshot installation
        run: |
          which appshot || echo "appshot command: $(which appshot)"
          appshot --version
      
      - name: Test init command
        run: |
          mkdir -p /tmp/test-init-${{ github.run_id }}
          cd /tmp/test-init-${{ github.run_id }}
          appshot init --force
          test -f .appshot/config.json
          test -d screenshots
          test -d .appshot/captions
      
      - name: Test specs and presets commands
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot specs --json > specs.json
          test -s specs.json
          appshot presets --json > presets.json
          test -s presets.json
          appshot presets --required > required.txt
          test -s required.txt
      
      - name: Test fonts command
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot fonts --json > fonts.json
          test -s fonts.json
          appshot fonts --validate "Arial" || echo "Font validation completed"
      
      - name: Create test screenshots
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          # Copy package.json and install sharp locally
          cat > package.json << 'EOF'
          {
            "name": "test-project",
            "type": "module",
            "dependencies": {
              "sharp": "^0.33.0"
            }
          }
          EOF
          npm install
          
          cat > create-screenshots.js << 'EOF'
          import sharp from 'sharp';
          import fs from 'fs/promises';
          
          // iPhone screenshot
          await sharp({
            create: {
              width: 1290,
              height: 2796,
              channels: 4,
              background: { r: 100, g: 150, b: 200, alpha: 1 }
            }
          })
          .png()
          .toFile('screenshots/iphone/home.png');
          
          // iPad screenshot
          await sharp({
            create: {
              width: 2048,
              height: 2732,
              channels: 4,
              background: { r: 200, g: 100, b: 150, alpha: 1 }
            }
          })
          .png()
          .toFile('screenshots/ipad/dashboard.png');
          
          // Watch screenshot
          await fs.mkdir('screenshots/watch', { recursive: true });
          await sharp({
            create: {
              width: 396,
              height: 484,
              channels: 4,
              background: { r: 150, g: 200, b: 100, alpha: 1 }
            }
          })
          .png()
          .toFile('screenshots/watch/glance.png');
          
          console.log('Test screenshots created');
          EOF
          node create-screenshots.js
      
      - name: Set captions programmatically
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          cat > .appshot/captions/iphone.json << 'EOF'
          {
            "home.png": "Welcome to our amazing app"
          }
          EOF
          cat > .appshot/captions/ipad.json << 'EOF'
          {
            "dashboard.png": "Powerful dashboard at your fingertips"
          }
          EOF
          cat > .appshot/captions/watch.json << 'EOF'
          {
            "glance.png": "Quick info"
          }
          EOF
      
      - name: Test gradients command
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot gradients --list
          appshot gradients --apply ocean
          grep -q "ocean" .appshot/config.json || echo "Gradient applied"
      
      - name: Test build command (no frame)
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot build --devices iphone,ipad,watch --no-frame
          test -f final/iphone/*/home.png || test -f final/iphone/home.png
          test -f final/ipad/*/dashboard.png || test -f final/ipad/dashboard.png
          test -f final/watch/*/glance.png || test -f final/watch/glance.png
      
      - name: Test clean command
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot clean
          test ! -d final || echo "Final directory cleaned"
      
      - name: Test build with frames
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot build --devices iphone
          test -f final/iphone/*/home.png || test -f final/iphone/home.png
      
      - name: Test validate command
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot validate || echo "Validation completed"
      
      - name: Test multi-language build
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          # Add multi-language captions
          cat > .appshot/captions/iphone.json << 'EOF'
          {
            "home.png": {
              "en": "Welcome to our app",
              "es": "Bienvenido a nuestra app",
              "fr": "Bienvenue dans notre app"
            }
          }
          EOF
          appshot build --devices iphone --langs en,es,fr --no-frame
          test -d final/iphone/en
          test -d final/iphone/es
          test -d final/iphone/fr
      
      - name: Test fonts --set command
        run: |
          cd /tmp/test-init-${{ github.run_id }}
          appshot fonts --set "Georgia" || echo "Font set"
          grep -q "Georgia" .appshot/config.json || echo "Font configured"
      
      - name: Upload integration test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-${{ matrix.os }}-${{ github.run_id }}
          path: |
            /tmp/test-init-${{ github.run_id }}/final/
            /tmp/test-init-${{ github.run_id }}/.appshot/
          retention-days: 7
      
      - name: Cleanup
        if: always()
        run: rm -rf /tmp/test-init-${{ github.run_id }}

  visual-validation:
    name: Visual Validation
    needs: cli-integration
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: integration-test-*
          merge-multiple: true
      
      - name: List downloaded files
        run: |
          echo "Downloaded artifacts:"
          find . -type f -name "*.png" | head -20
      
      - name: Verify screenshot properties
        run: |
          # Install imagemagick for image analysis
          sudo apt-get update && sudo apt-get install -y imagemagick
          
          # Check if screenshots exist and have correct properties
          for img in $(find . -name "*.png" | head -5); do
            echo "Analyzing: $img"
            identify -verbose "$img" | grep -E "Geometry:|Colorspace:|Format:" || true
          done
      
      - name: Create validation report
        run: |
          cat > validation-report.md << 'EOF'
          # Visual Validation Report
          
          ## Screenshots Generated
          EOF
          
          echo "### iPhone Screenshots" >> validation-report.md
          find . -path "*/iphone/*.png" -type f | while read f; do
            echo "- $(basename $f)" >> validation-report.md
          done
          
          echo "### iPad Screenshots" >> validation-report.md
          find . -path "*/ipad/*.png" -type f | while read f; do
            echo "- $(basename $f)" >> validation-report.md
          done
          
          echo "### Watch Screenshots" >> validation-report.md
          find . -path "*/watch/*.png" -type f | while read f; do
            echo "- $(basename $f)" >> validation-report.md
          done
          
          echo "" >> validation-report.md
          echo "## Test Status: ✅ Passed" >> validation-report.md
          
          cat validation-report.md
      
      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-${{ github.run_id }}
          path: validation-report.md
          retention-days: 7