name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Check bundle size
        run: |
          echo "## 📦 Bundle Size Report"
          echo "Total dist size:"
          du -sh dist/
          echo ""
          echo "File sizes:"
          find dist -name "*.js" -exec du -h {} \; | sort -h

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Test CLI commands
        run: |
          node dist/cli.js --version
          node dist/cli.js --help
          node dist/cli.js init --help
          node dist/cli.js build --help
          node dist/cli.js presets --help
          node dist/cli.js validate --help
      
      - name: Test init command (dry run)
        run: |
          mkdir test-project
          cd test-project
          node ../dist/cli.js init --force
          test -d .appshot
          test -f .appshot/config.json
          cat .appshot/config.json